### GET hello
GET http://localhost:8888/hello

### GET gw 1
GET http://localhost:8888/gw



### POST midnight-rpc
POST http://localhost:8888/gw/midnight-rpc/com.midnight.rpc.demo.api.UserService
Content-Type: application/json

{
  "service":"com.midnight.rpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}

### POST direct
POST http://localhost:8888/gw/direct/com.midnight.rpc.demo.api.UserService
Content-Type: application/json

{
  "service":"com.midnight.rpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}


### POST direct backend
POST http://localhost:8888/gw/direct//com.midnight.rpc.demo.api.UserService?backend=http://localhost:8082/midnight-rpc
Content-Type: application/json

{
  "service":"com.midnight.rpc.demo.api.UserService",
  "methodSign":"findById@1_int",
  "args":[100]
}


